# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.  

name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  tag: $(date +%s)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Build the Docker image
      run: docker build -t registry.cn-hangzhou.aliyuncs.com/yido/websocket:$GITHUB_RUN_ID .
    - name: Login Docker
      run: docker login --username=a549137619 --password=leime727299 registry.cn-hangzhou.aliyuncs.com
    - name: Push Docker Image
      run: docker push registry.cn-hangzhou.aliyuncs.com/yido/websocket:$GITHUB_RUN_ID
    - name: deploy service
      uses: appleboy/ssh-action@v1.0.0
      env: 
        run_id: "$GITHUB_RUN_ID"
      with:
        host: 121.41.72.174
        username: root
        password: Abc123456
        script: |
            echo "$run_id"
            echo "install docker..."
            test -f /opt/idcos-docker/docker-deploy.sh || curl -o /opt/idcos-docker/docker-deploy.sh http://yum.idcos.com/opensource/docker/docker-deploy.sh
            bash /opt/idcos-docker/docker-deploy.sh
            echo "login docker..."
            docker login --username=a549137619 --password=leime727299 registry.cn-hangzhou.aliyuncs.com
            docker pull registry.cn-hangzhou.aliyuncs.com/yido/websocket:${{ github.run_id }}
            echo "start service...."
            docker run -p 8080:8080 -d registry.cn-hangzhou.aliyuncs.com/yido/websocket:${{ github.run_id }}
